INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MYTUTORIAL mytutorial)

FIND_PATH(
    MYTUTORIAL_INCLUDE_DIRS
    NAMES mytutorial/api.h
    HINTS $ENV{MYTUTORIAL_DIR}/include
        ${PC_MYTUTORIAL_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MYTUTORIAL_LIBRARIES
    NAMES gnuradio-mytutorial
    HINTS $ENV{MYTUTORIAL_DIR}/lib
        ${PC_MYTUTORIAL_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MYTUTORIAL DEFAULT_MSG MYTUTORIAL_LIBRARIES MYTUTORIAL_INCLUDE_DIRS)
MARK_AS_ADVANCED(MYTUTORIAL_LIBRARIES MYTUTORIAL_INCLUDE_DIRS)

